name: Github Actions Demo
on: 
  push:
    branches:
      - develop1
  pull_request:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello Work"
      - name: This step checks out a copy of your repository.
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: npm
      - name: install node 
        run: npm i
      - name: eslint
        run: npm run lint
      