name: Github Actions Demo
on:
  # push: 
  #   branches:
  #     - develop1
  # pull_request:
  issues:
    types:
      - reopened
      - opened
      - closed
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: This step checks out a copy of your repository.
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x
          cache: npm
      - name: install node
        run: npm i
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          eslint_flags: 'src/'
      - name: eslint
        run: npm run lint
